# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{otp-kickoff}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Leandro Silva"]
  s.date = %q{2009-10-19}
  s.default_executable = %q{otp-kickoff}
  s.email = %q{leandrodoze@gmail.com}
  s.executables = ["otp-kickoff"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/otp-kickoff",
     "lib/otp-kickoff.rb",
     "otp-kickoff.gemspec",
     "otp-kickoff.rb",
     "resources/template_app.app",
     "resources/template_app.erl",
     "resources/template_appstart.erl",
     "resources/template_handler.erl",
     "resources/template_include.hrl",
     "resources/template_server.erl",
     "resources/template_sup.erl",
     "spec/otp-kickoff_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/leandrosilva/otp-kickoff}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Simple generator to kick off Erlang/OTP projects}
  s.test_files = [
    "spec/otp-kickoff_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<wycats-thor>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<wycats-thor>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<wycats-thor>, [">= 0"])
  end
end
